### ISSUE TITLE
Getting the postal for another script that can display it in text

### ISSUE THREAD

**Issue by ViolentMinds** [DevBlocky/nearest-postal#13]
Any lua coders know how I could display the postal in another script?
I want to display the postals in 911 calls that are automated.
But not sure what export if possible I can use or what I can do to reference the postal from this script.

I did notice: `exports('getPostal', function() return nearest and nearest.code or nil end)` in cl.lua

and my code: `local postal = exports["nearest-postal"]:getPostal()	`

But yet I get errors for `No such export getPostal in resource nearest-postal`

any ideas?

cc: @DevBlocky @GoatG33k @MichaelCoding25 @DawsonGodin

**Comment by ViolentMinds** [comment]
I also tried adding the exports to the fxmanifest of nearest-postal resource and the dependency to fxmanifest of the 911 script I am using
from nearest-postal fxmanifest 

```
exports {
    "getPostal"
}

server_exports {
    "getPostal"
}
```


from my resource fxmanifest:       `dependency "nearest-postal"`

**Comment by ViolentMinds** [comment]
Managed to get it to work with some changes.

**Comment by ResqDiver1317** [comment]
@Legacy-TacticalGamingInteractive Can you tell me how you got it to work? I'm trying to setup a simple teleport to AOP script but adding a chat message for when it's used to prevent people from abusing it while in the AOP already so I want it to tell me what postal they came from.

**Comment by Legacy-TacticalGamingInteractive** [comment]
> @Legacy-TacticalGamingInteractive Can you tell me how you got it to work? I'm trying to setup a simple teleport to AOP script but adding a chat message for when it's used to prevent people from abusing it while in the AOP already so I want it to tell me what postal they came from.

sorry bro i dont use nearest postal anymore sorry i cant be more help because i dont have the files anymore and no clue what we did as it was a while back
