### ISSUE TITLE
This isnt't an issue an issue but a question!

### ISSUE THREAD

**Issue by KillaNAdev** [DevBlocky/nearest-postal#9]
Hello, I am trying to modify this to work with my 911 command so the postal shows up for whoever reports I heard there was an export GetPostal() but it isn't working if you could help me that would be great!

**Comment by PhantomAwe** [comment]
exports('getPostal', function() return nearest and nearest.code or nil end) 

here is the export I believe can be found in cl.lua

or

exports('getPostalServer', function(coords)
    return getPostalServer(coords)
end)

this is the sv.lua export
